baseurl = "/"
languageCode = "en-us"
title = "flatpickr"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
    # General information
    author = "chmln"
    description = "A lightweight and powerful datetimepicker"
    copyright = "Released under the MIT license"

    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/chmln/flatpickr"

    version = "v2.3.7"
    logo = "images/logo.png"
    favicon = ""

    permalink = "#"

    # Custom assets
    custom_css = []
    custom_js  = []

    # Syntax highlighting theme
    highlight_css  = ""

    [params.palette]
        primary = "blue"
        accent  = "light-blue"

    [params.font]
        text = "Libre Franklin"
        code = "Roboto Mono"


[social]
    twitter = ""
    github  = "chmln"
    email   = "hello@email.com"


[[menu.main]]
    name   = "Intro"
    url    = "/"
    weight = 0

[[menu.main]]
    name   = "Getting Started"
    url    = "getting-started/"
    weight = 10

[[menu.main]]
    name   = "Examples"
    url    = "examples/"
    weight = 20

[[menu.main]]
    name   = "Options"
    url    = "options/"
    weight = 30


[blackfriday]
    smartypants = true
    fractions = true
    smartDashes = true
    plainIDAnchors = true
